version: '2'
services:

  db:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_DATABASE: bc_25_gc
      MYSQL_USER: gc
      MYSQL_PASSWORD: Gc@12345
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./Database_bc25/:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306  

  backend:
    build:
      context: ./backend  
    restart: always  
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/bc_25_gc?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: gc
      SPRING_DATASOURCE_PASSWORD: Gc@12345   
    ports:
     - 8000:8000     
    depends_on:
     - db 

  frontend:
    build:
      context:  ./frontend
    ports: 
      - 8080:8080
    depends_on:
     - backend 
        
