name: deploy frontend

on:
  push:
    branch:
      - docker-image

jobs:
  build:
    name: build and push docker images for frontend and backend
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v2  
      - name: create target folder
        run: mvn -f ./backend/pom.xml clean install -DskipTests=true  
      - name: login to github container registry
        uses: docker/login-action@v1
        with:
           registry: ghcr.io
           username: bharti2022
           password: ${{secrets.REPO_TOKEN}}      
      - name: docker build frontend
        run: docker build ./frontend/ -t ghcr.io/bharti2022/green-commute-frontend:latest
      - name: docker push  frontend
        run: docker push ghcr.io/bharti2022/green-commute-frontend:latest
      - name: docker build backend
        run: docker build ./backend/ -t ghcr.io/bharti2022/green-commute-backend:latest
      - name: docker push  backend
        run: docker push ghcr.io/bharti2022/green-commute-backend:latest
      - name: build database 
        run: docker build ./Database_bc25/ -t ghcr.io/bharti2022/green-commute-db:latest
      - name: docker push database
        run: docker push ghcr.io/bharti2022/green-commute-db:latest
           